### ISSUE TITLE
CSV formatında veri paylaşımı

### ISSUE THREAD

**Issue by nuriakman** [AlperKocanx/TurkiyeGuncelSehirIlceMahalleBilgileri2022#1]
Merhaba, bu güzel verileri CSV formatında da paylaşabilir misiniz?

Verdiğiniz dosya MySQL için uygun olmadığı için kullanamadığım için bunu istiyorum.

İyi çalışmalar dilerim...

**Comment by AlperKocanx** [comment]
Merhaba,

Talebiniz üzerine dosyayı oluşturdum. Aşağıdan erişebilirsiniz.

İyi çalışmalar.

[AdresListesi.csv](https://github.com/AlperKocanx/TurkiyeGuncelSehirIlceMahalleBilgileri2022/files/13785412/AdresListesi.csv)

**Comment by nuriakman** [comment]
Çok teşekkür ederim :)
